### ISSUE TITLE
Remove redundant implementations of Capsule

### ISSUE THREAD

**Issue by Devin97** [OpenMined/Capsule#9]
After implementing ZeroMQ in capsule, we figured out that Django server is not getting used at all and since all communications between other modules and capsule is being handled by ZeroMQ,  we don't really need Django or Flask server.

There are 3 capsule implementations using different frameworks (ZeroMQ, Django and Flask). So to remove the confusion, we should remove Django and Flask implementation of capsule and only keep ZeroMQ implementation of Capsule.

**Comment by pandey-vaibhav** [comment]
Agree !!

**Comment by aradhyamathur** [comment]
I think we should let it remain since it provides the developers with the choice to go ahead with their choice of framework and help us expand our reach as well in different communities. So we could let those remain as well since all the three though might seem redundant but have different ideologies behind them. One showing simple message passing , others showing different server side implementations.

**Comment by Devin97** [comment]
I don't think we are ever going to use these implementations, so keeping these doesn't make any sense.

**Comment by aradhyamathur** [comment]
hmm @iamtrask what do u say ? Shall we go ahead.

**Comment by iamtrask** [comment]
We definitely shouldn't leave all 3 in their current state, where we have to maintain identical functionality across all 3. If anyone wants to build the abstraction necessary to make it so that they all consume the same code......


...yeah we should probably go ahead.... ZeroMQ is going to be loads faster in the long run.
